version: '3.8'

## Please read README.md first to setup udev rules##

services:
  arucotag:
    build: 
      context: .  
      dockerfile: Dockerfile
    image: renee0630/realsense-noetic-root:arucoros
    container_name: arucoros
    command: /bin/bash 
    tty: true  
    network_mode: host
    privileged: true 

    ## accessibility to Intel® RealSense™ 
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}  # Set display environment variable
      - XAUTHORITY=/root/.Xauthority   # Set Xauthority path
    devices:
      - /dev/bus/usb  # Grant access to USB devices


